# Site Settings
locale                   : "en-US"
title                    : "Japheth Mursi"
title_separator          : "-"
name                     : &name "Japheth Mursi"
description              : &description "AI Researcher | Financial Literacy Advocate"
url                      : https://jmursi.github.io
baseurl                  : "" # leave blank if not in a subfolder
repository               : "jmursi/jmursi.github.io"
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : false
read_more                : "disabled"
talkmap_link             : false

# Comments
comments:
  provider: false

# Atom Feed
atom_feed:
  path: # blank uses default feed.xml

# SEO
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username: japhethmursi

# Social Profiles
social:
  type: Person
  name: Japheth Mursi
  links:
    - https://github.com/jmursi
    - https://ke.linkedin.com/in/japheth-mursi
    - https://scholar.google.com/citations?user=f0LGF3wAAAAJ&hl=en

# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: # Add your tracking ID if needed

# Author
author:
  name             : "Japheth Mursi"
  avatar           : "jmursidp.jpeg"
  bio              : "AI Researcher | Financial Literacy Advocate"
  location         : "Nairobi, Kenya"
  email            : "mursijapheth@gmail.com"
  github           : "jmursi"
  linkedin         : "japheth-mursi"
  googlescholar    : "https://scholar.google.com/citations?user=f0LGF3wAAAAJ&hl=en"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  misc:
    output: true
    permalink: /:collection/:path/
  experience:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: experience
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

  - scope:
      path: ""
      type: misc
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Africa/Nairobi

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
